---
title: "RHETORIC; CURRENT-TRADITIONAL"
description: "RHETORIC; EPISTEMIC RHETORIC; PERELMAN,"
---

RHETORIC; EPISTEMIC RHETORIC; PERELMAN,
CHAIM; POSTSTRUCTURALISM; RICHARDS,
LA.; TOULMIN, STEVEN; WEAVER, RICHARD;
