---
title: "P"
description: "Encyclopedia entries beginning with P"
---

# P

- [Parenthesis](/docs/p/parenthesis)
- [Partitio](/docs/p/partitio)
- [Pathos](/docs/p/pathos)
- [PENTAD; SYMBOLIC ACTION](/docs/p/pentad-symbolic-action)
- [PENTAD; TAGMEMICS; TECHNÊ; TOPICS](/docs/p/pentad-tagmemics-techn-topics)
- [Pentad](/docs/p/pentad)
- [Peripatetics](/docs/p/peripatetics)
- [Periphrasis](/docs/p/periphrasis)
- [Peroratio](/docs/p/peroratio)
- [Persona](/docs/p/persona)
- [PERSUASION; POLITICAL RHETORIC](/docs/p/persuasion-political-rhetoric)
- [PERSUASION](/docs/p/persuasion)
- [Phronésis](/docs/p/phron-sis)
- [Pizan, Christine de (1364–c. 1430)](/docs/p/pizan-christine-de-1364-c-1430)
- [Pleonasm](/docs/p/pleonasm)
- [Ploce](/docs/p/ploce)
- [Poetics](/docs/p/poetics)
- [Polyptoton](/docs/p/polyptoton)
- [Polysyndeton](/docs/p/polysyndeton)
- [Port-Royalists](/docs/p/port-royalists)
- [Portfolio](/docs/p/portfolio)
- [Postmodernism](/docs/p/postmodernism)
- [POSTSTRUCTURALISM](/docs/p/poststructuralism)
- [Pragmatism](/docs/p/pragmatism)
- [Praxis](/docs/p/praxis)
- [Preteritio](/docs/p/preteritio)
- [Probability](/docs/p/probability)
- [Process/Product](/docs/p/process-product)
- [PROJECT; PROTOCOLS](/docs/p/project-protocols)
- [Prolegomena](/docs/p/prolegomena)
- [PROOF](/docs/p/proof)
- [PROPAGANDA](/docs/p/propaganda)
- [Protest Rhetoric](/docs/p/protest-rhetoric)
- [Protocols](/docs/p/protocols)
- [PULPIT ORATORY; SERMON](/docs/p/pulpit-oratory-sermon)
